// webpack.config.js

var webpack = require('webpack');
var path = require('path');
var libraryName = 'asar.lib';
var outputFile = libraryName + '.js';
var externals = require('webpack-node-externals')({
  whitelist: [
    'minimatch', 
    'mkdirp', 
    'brace-expansion', 
    'cuint', 
    'chromium-pickle-js', 
    'glob', 
    'mksnapshot', 
    'path-is-absolute',
    'concat-map',
    'balanced-match',
    '@types',
    'abbrev',
    'acorn',
    'acorn-jsx',
    'ajv','ajv-keywords',
    'ansi-escapes',
    'ansi-regex',
    'ansi-styles',
    'aproba',
    'argparse',
    'array-find-index',
    'array-union',
    'array-uniq',
    'arrify',
    'asn1',
    'assert-plus',
    'asynckit',
    'aws4',
    'aws-sign2',
    'babel-code-frame',
    'babel-core',
    'babel-generator',
    'babel-helper-bindify-decorators',
    'babel-helper-builder-binary-assignment-operator-visitor',
    'babel-helper-call-delegate',
    'babel-helper-define-map',
    'babel-helper-explode-assignable-expression',
    'babel-helper-explode-class',
    'babel-helper-function-name',
    'babel-helper-get-function-arity',
    'babel-helper-hoist-variables',
    'babel-helper-optimise-call-expression',
    'babel-helper-regex',
    'babel-helper-remap-async-to-generator',
    'babel-helper-replace-supers',
    'babel-helpers',
    'babel-loader',
    'babel-messages',
    'babel-plugin-check-es2015-constants',
    'babel-plugin-syntax-async-functions',
    'babel-plugin-syntax-async-generators',
    'babel-plugin-syntax-class-properties',
    'babel-plugin-syntax-decorators',
    'babel-plugin-syntax-dynamic-import',
    'babel-plugin-syntax-exponentiation-operator',
    'babel-plugin-syntax-object-rest-spread',
    'babel-plugin-syntax-trailing-function-commas',
    'babel-plugin-transform-async-generator-functions',
    'babel-plugin-transform-async-to-generator',
    'babel-plugin-transform-class-properties',
    'babel-plugin-transform-decorators',
    'babel-plugin-transform-es2015-arrow-functions',
    'babel-plugin-transform-es2015-block-scoped-functions',
    'babel-plugin-transform-es2015-block-scoping',
    'babel-plugin-transform-es2015-classes',
    'babel-plugin-transform-es2015-computed-properties',
    'babel-plugin-transform-es2015-destructuring',
    'babel-plugin-transform-es2015-duplicate-keys',
    'babel-plugin-transform-es2015-for-of',
    'babel-plugin-transform-es2015-function-name',
    'babel-plugin-transform-es2015-literals',
    'babel-plugin-transform-es2015-modules-amd',
    'babel-plugin-transform-es2015-modules-commonjs',
    'babel-plugin-transform-es2015-modules-systemjs',
    'babel-plugin-transform-es2015-modules-umd',
    'babel-plugin-transform-es2015-object-super',
    'babel-plugin-transform-es2015-parameters',
    'babel-plugin-transform-es2015-shorthand-properties',
    'babel-plugin-transform-es2015-spread',
    'babel-plugin-transform-es2015-sticky-regex',
    'babel-plugin-transform-es2015-template-literals',
    'babel-plugin-transform-es2015-typeof-symbol',
    'babel-plugin-transform-es2015-unicode-regex',
    'babel-plugin-transform-exponentiation-operator',
    'babel-plugin-transform-object-rest-spread',
    'babel-plugin-transform-regenerator',
    'babel-plugin-transform-strict-mode',
    'babel-preset-es2015',
    'babel-preset-stage-2',
    'babel-preset-stage-3',
    'babel-register',
    'babel-runtime',
    'babel-template',
    'babel-traverse',
    'babel-types',
    'babylon',
    'balanced-match',
    'bcrypt-pbkdf',
    'big.js',
    'binary',
    'bluebird',
    'boom',
    'brace-expansion',
    'browser-stdout',
    'buffers',
    'builtin-modules',
    'cacache',
    'caller-path',
    'callsites',
    'camelcase',
    'camelcase-keys',
    'caseless',
    'chainsaw',
    'chalk',
    'chownr',
    'chromium-pickle-js',
    'circular-json',
    'cli-cursor',
    'cli-width',
    'co',
    'code-point-at',
    'combined-stream',
    'commander',
    'commondir',
    'concat-map',
    'concat-stream',
    'convert-source-map',
    'copy-concurrently',
    'core-js',
    'core-util-is',
    'cryptiles',
    'cuint',
    'currently-unhandled',
    'cyclist',
    'd',
    'dashdash',
    'debug',
    'debug-log',
    'decamelize',
    'decompress-zip',
    'deep-extend',
    'deep-is',
    'deglob',
    'del',
    'delayed-stream',
    'detect-indent',
    'diff',
    'doctrine',
    'duplexify',
    'ecc-jsbn',
    'electron',
    'electron-download',
    'electron-mocha',
    'electron-window',
    'emojis-list',
    'end-of-stream',
    'errno',
    'error-ex',
    'es5-ext',
    'es6-iterator',
    'es6-map',
    'es6-promise',
    'es6-set',
    'es6-symbol',
    'es6-weak-map',
    'escape-string-regexp',
    'escope',
    'eslint',
    'eslint-config-standard',
    'eslint-config-standard-jsx',
    'eslint-plugin-promise',
    'eslint-plugin-react',
    'eslint-plugin-standard',
    'espree',
    'esprima',
    'esrecurse',
    'estraverse',
    'esutils',
    'event-emitter',
    'exit-hook',
    'extend',
    'extract-zip',
    'extsprintf',
    'fast-deep-equal',
    'fast-json-stable-stringify',
    'fast-levenshtein',
    'fd-slicer',
    'figures',
    'file-entry-cache',
    'find-cache-dir',
    'find-root',
    'find-up',
    'flat-cache',
    'flush-write-stream',
    'forever-agent',
    'form-data',
    'from2',
    'fs.realpath',
    'fs-extra',
    'fs-write-stream-atomic',
    'generate-function',
    'generate-object-property',
    'getpass',
    'get-stdin',
    'glob',
    'globals',
    'globby',
    'graceful-fs',
    'graceful-readlink',
    'growl',
    'har-schema',
    'har-validator',
    'has-ansi',
    'has-flag',
    'hawk',
    'he','hoek','home-or-tmp','home-path','hosted-git-info','http-signature','iferr','ignore','imurmurhash','indent-string','inflight','inherits','ini','inquirer','interpret','invariant','isarray','is-arrayish','is-builtin-module','is-electron-renderer','isexe','is-finite','is-fullwidth-code-point','is-my-json-valid','is-path-cwd','is-path-in-cwd','is-path-inside','is-property','is-resolvable','isstream','is-typedarray','is-utf8','jade','jsbn','jsesc','json3','json5','jsonfile','jsonify','jsonpointer','json-schema','json-schema-traverse','json-stable-stringify','json-stringify-safe','jsprim','js-tokens','jsx-ast-utils','js-yaml','klaw','levn','loader-utils','load-json-file','locate-path','lodash','lodash._baseassign','lodash._basecopy','lodash._basecreate','lodash._getnative','lodash._isiterateecall','lodash.create','lodash.isarguments','lodash.isarray','lodash.keys','loose-envify','loud-rejection','lru-cache','make-dir','map-obj','meow','mime-db','mime-types','minimatch','minimist','mississippi','mkdirp','mkpath','mksnapshot','mocha','move-concurrently','ms','mute-stream','natural-compare','nopt','normalize-package-data','nugget','number-is-nan','oauth-sign','object-assign','object-keys','once','onetime','optionator','os-homedir','os-tmpdir','parallel-transform','parse-json','path-exists','path-is-absolute','path-is-inside','path-parse','path-type','pend','performance-now','pify','pinkie','pinkie-promise','pkg-config','pkg-dir','p-limit','p-locate','pluralize','prelude-ls','pretty-bytes','private','process-nextick-args','progress','progress-stream','promise-inflight','prr','pseudomap','p-try','pump','pumpify','punycode','q','qs','rc','readable-stream','readline2','read-pkg','read-pkg-up','rechoir','redent','regenerate','regenerator-runtime','regenerator-transform','regexpu-core','regjsgen','regjsparser','repeating','request','require-uncached','resolve','resolve-from','restore-cursor','rimraf','run-async','run-parallel','run-queue','rx-lite','safe-buffer','schema-utils','semver','serialize-javascript','shelljs','sigmund','signal-exit','single-line-log','slash','slice-ansi','sntp','source-list-map','source-map','source-map-support','spdx-correct','spdx-expression-parse','spdx-license-ids','speedometer','sprintf-js','sshpk','ssri','standard','standard-engine','stream-each','stream-shift','string_decoder','stringstream','string-width','strip-ansi','strip-bom','strip-indent','strip-json-comments','sumchecker','supports-color','table','text-table','throttleit','through','through2','tmp','to-fast-properties','to-iso-string','touch','tough-cookie','traverse','trim-newlines','trim-right','tryit','tunnel-agent','tweetnacl','type-check','typedarray','uglify-es','uglifyjs-webpack-plugin','uniq','unique-filename','unique-slug','universalify','user-home','util-deprecate','uuid','validate-npm-package-license','verror','webpack-node-externals','webpack-sources','which','wordwrap','worker-farm','wrappy','write','xtend','xvfb-maybe','y18n','yallist','yauzl'
  ]
  
})

var config = {
  entry: __dirname + '/lib/asar.js',
  //devtool: 'source-map',
  target: 'node',
  externals: ['original-fs', externals],
  context: __dirname,
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: outputFile,
    library: libraryName,
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015'],
            plugins: [require('babel-plugin-transform-object-rest-spread')]
          }
        }
      }
    ]
  },
  plugins: [
    new (require('uglifyjs-webpack-plugin'))({

    })
  ]
};

module.exports = config;
